name: flutter3_widgets
description: flutter3 widgets package
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

# https://dart.dev/tools/pub/workspaces/
# Support for pub workspaces was introduced in Dart 3.6.0.
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter3_res:
    path: ../flutter3_res
  flutter3_basics:
    path: ../flutter3_basics

  # https://pub.dev/packages/sliver_tools
  # https://github.com/Kavantix/sliver_tools
  sliver_tools: ^0.2.12

  # https://pub.dev/packages/lifecycle
  # https://github.com/chenenyu/lifecycle
  lifecycle: ^0.10.0

  # https://pub.dev/packages/expandable
  # https://github.com/aryzhov/flutter-expandable
  expandable: ^5.0.1

  # https://pub.dev/packages/rich_readmore
  # https://github.com/thierryoliveira/rich_readmore
  rich_readmore: ^1.1.1

  # https://pub.dev/packages/flutter_slidable
  # https://github.com/letsar/flutter_slidable
  # hashValues
  flutter_slidable: ^4.0.0

  # https://pub.dev/packages/flutter_verification_code
  # https://github.com/awaik/flutter_verification_code
  # flutter_verification_code: ^1.1.7

  # https://pub.dev/packages/wheel_picker
  # https://github.com/stavgafny/wheel_picker
  wheel_picker: ^0.2.2

  # https://pub.dev/packages/list_wheel_scroll_view_nls
  # https://github.com/JoDeveloper/list_wheel_scroll_view_nls
  list_wheel_scroll_view_nls: ^0.0.3

  # https://pub.dev/packages/badges
  # https://github.com/yako-dev/flutter_badges
  badges: ^3.1.2

  # https://pub.dev/packages/flutter_constraintlayout
  flutter_constraintlayout: ^1.7.0-stable

  # https://pub.dev/packages/scrollview_observer
  scrollview_observer: ^1.26.2

  # https://pub.dev/packages/flutter_rating_bar
  flutter_rating_bar: ^4.0.1

  # https://pub.dev/packages/visibility_detector
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/flutter_lints # lints
  flutter_lints: any
  # https://pub.dev/packages/build_runner
  # https://pub.dev/packages/web_socket_channel # async, crypto, stream_channel, web
  # https://pub.dev/packages/stream_channel
  # https://pub.dev/packages/async # collection, meta
  # https://pub.dev/packages/web
  build_runner: any
  # https://pub.dev/packages/flutter_gen_runner
  flutter_gen_runner: any

# https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  output: lib/assets_generated/ # Optional (default: lib/gen/)
  parse_metadata: true
  assets:
    outputs:
      package_parameter_enabled: true
      directory_path_enabled: true
  integrations:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # assets:
    #- assets/png/
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
