name: flutter3_opencv
description: "A Flutter OpenCV package."
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The minimum required dart sdk version is 3.10 (Flutter 3.38) that supports hooks (Native-Assets).
# 最低要求的 Dart SDK 版本为 3.10 （Flutter 3.38 ），支持 hooks（Native-Assets）。
environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

# https://dart.dev/tools/pub/workspaces/
# Support for pub workspaces was introduced in Dart 3.6.0.
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/opencv_dart
  # https://pub.dev/packages/dartcv4
  opencv_dart: ^2.2.1+4
  # https://pub.dev/packages/dartcv4
  # https://pub.dev/packages/code_assets
  # https://pub.dev/packages/ffi
  # https://pub.dev/packages/hooks
  # https://pub.dev/packages/logging
  # https://pub.dev/packages/native_toolchain_cmake

  #opencv_dart: ^1.4.3
  #dartcv4: ^1.1.8

  flutter3_basics:
    path: ../flutter3_basics

dependency_overrides:
  # https://pub.dev/packages/dartcv4
  # 系统需要安装 CMake
  #dartcv4: ^2.2.1 # 2.2.0 OpenCV 4.13.0

# 需要在主工程配置
hooks:
  user_defines:
    dartcv4:
      # debug: true
      include_modules: # `core` is always included
        - imgcodecs
        - imgproc
        #- contrib
        - ximgproc
        - calib3d
        # ...
      exclude_modules:
      # - imgcodecs
      # - imgproc
      # - ...
      # - calib3d
      # - contrib
      # - dnn
      # - features2d
      # - freetype
      # - highgui
      # - objdetect
      # - photo
      # - stitching
      # - video
      # - videoio
      # - aruco
      # - img_hash
      # - quality
      # - wechat_qrcode
      # - ximgproc
      # - xobjdetect

dev_dependencies:
  flutter_test:
    sdk: flutter
  # in flutter3_basics
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
