name: flutter3_pub_core
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

# https://dart.dev/tools/pub/workspaces/
# Support for pub workspaces was introduced in Dart 3.6.0.
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter3_basics:
    path: ../flutter3_basics
  flutter3_widgets:
    path: ../flutter3_widgets

  # https://pub.dev/packages/easy_refresh
  # https://pub.dev/packages/path_drawing
  easy_refresh: ^3.4.0

  # https://pub.dev/packages/el_tooltip
  #el_tooltip: ^2.2.1
  el_tooltip:
    git:
      url: git@github.com:FlutterStudioIst/el_tooltip.git
      ref: 2.2.1-fix2

  # https://pub.dev/packages/rxdart
  rxdart: ^0.28.0

  # https://pub.dev/packages/get_it
  # https://pub.dev/packages/async
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/meta
  get_it: ^8.2.0

  # https://pub.dev/packages/watch_it
  # https://pub.dev/packages/functional_listener
  # https://pub.dev/packages/get_it
  watch_it: ^1.7.0

  # https://pub.dev/packages/go_router
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/flutter_web_plugins
  # https://pub.dev/packages/logging
  # https://pub.dev/packages/meta
  go_router: ^16.3.0
  # https://pub.dev/packages/logging
  logging: ^1.3.0

  # https://pub.dev/packages/wakelock_plus
  # https://pub.dev/packages/dbus
  # iOS 12.0 or higher
  # macOS 10.15 or higher
  wakelock_plus: ^1.4.0
  # https://pub.dev/packages/keep_screen_on
  # keep_screen_on: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
