name: flutter3_mcp
description: "A new Flutter Model Context Protocol project."
version: 0.0.1
homepage: https://github.com/angcyo/Flutter3Core
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

# https://dart.dev/tools/pub/workspaces/
# Support for pub workspaces was introduced in Dart 3.6.0.
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter3_basics:
    path: ../flutter3_basics
  flutter3_core:
    path: ../flutter3_core
  flutter3_http:
    path: ../flutter3_http
  flutter3_shelf:
    path: ../flutter3_shelf

  # https://pub.dev/packages/mcp_dart
  # https://pub.dev/packages/http
  mcp_dart: ^1.2.1

#  # https://pub.dev/packages/dart_mcp
#  # https://pub.dev/packages/async
#  # https://pub.dev/packages/collection
#  # https://pub.dev/packages/json_rpc_2
#  # https://pub.dev/packages/meta
#  # https://pub.dev/packages/stream_channel
#  # https://pub.dev/packages/stream_transform
#  dart_mcp: ^0.4.0
#  # https://pub.dev/packages/stack_trace
#  # https://pub.dev/packages/stream_channel
#  json_rpc_2: ^4.0.0
#  # https://pub.dev/packages/stream_channel
#  stream_channel: ^2.1.4
#  # https://pub.dev/packages/stream_transform
#  stream_transform: ^2.1.1

  # https://pub.dev/packages/async
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/meta
  async: ^2.13.0

  # https://pub.dev/packages/dds
  # https://pub.dev/packages/dap
  # https://pub.dev/packages/dtd
  # https://pub.dev/packages/args
  # https://pub.dev/packages/sse
  # https://pub.dev/packages/json_rpc_2
  # https://pub.dev/packages/http_multi_server
  #dds: ^5.1.0
  # https://pub.dev/packages/dap
  #dap: ^1.4.0
  # https://pub.dev/packages/dtd
  #dtd: ^4.0.0
  # https://pub.dev/packages/sse
  # https://pub.dev/packages/async
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/logging
  # https://pub.dev/packages/pool
  # https://pub.dev/packages/shelf
  # https://pub.dev/packages/stream_channel
  # https://pub.dev/packages/web
  #sse: ^4.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
